apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
      - name: todo-app-volume
        persistentVolumeClaim:
          claimName: log-and-ping-pong-claim
      containers:
      - name: todo-app
        image: berkturetkenwartsila/the_project:0.3
        volumeMounts:
        - name: todo-app-volume
          mountPath: /app/files
