apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
  - todo_backend/manifests/configmap.yaml
  - todo_backend/manifests/statefulset.yaml
  - todo_backend/manifests/db-service.yaml
  - todo_backend/manifests/deployment.yaml
  - todo_backend/manifests/service.yaml
  - todo_backend/manifests/ingress.yaml
  - todo_frontend/manifests/configmap.yaml
  - todo_frontend/manifests/persistentvolumeclaim.yaml
  - todo_frontend/manifests/deployment.yaml
  - todo_frontend/manifests/service.yaml
  - todo_frontend/manifests/ingress.yaml
  - todo_generator/manifests/cronjob.yaml
