apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      volumes:
      - name: todo-frontend-volume
        persistentVolumeClaim:
          claimName: first-simple-claim
      containers:
      - name: todo-frontend
        image: berkturetkenwartsila/todo_frontend:0.2
        volumeMounts:
        - name: todo-frontend-volume
          mountPath: /app/files