apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-frontend
spec:
  replicas: 1
  strategy:
    type: Recreate # Use Recreate strategy for ReadWriteOnce volumes
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      volumes:
        - name: todo-frontend-volume
          persistentVolumeClaim:
            claimName: todo-app-claim
      containers:
        - name: todo-frontend
          image: TODO_FRONTEND_IMAGE_FROM_KUSTOMIZATION # this will be replaced by kustomize
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: todo-frontend-volume
              mountPath: /app/files
          # configuring *all* key-value pairs in ConfigMap as (container) environment variables
          envFrom:
            - configMapRef:
                name: todo-frontend-configmap
