apiVersion: batch/v1
kind: CronJob
metadata:
  name: wiki-todo-generator
  namespace: project
spec:
  schedule: "0 0,12 * * *" # Run at midnight and noon
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wiki-todo-generator
              image: TODO_GENERATOR_IMAGE_FROM_KUSTOMIZATION # this will be replaced by kustomize
              envFrom:
                - configMapRef:
                    name: todo-backend-configmap
          restartPolicy: OnFailure
