apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: todo-backend-configmap
data:
  PORT: "8090"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "todo_db"
  POSTGRES_USER: "todo_user"
  POSTGRES_PASSWORD: "todo_pass" # TODO: use Secret with SOPS here (see https://courses.mooc.fi/org/uh-cs/courses/devops-with-kubernetes/chapter-3/configuring-applications)
  PROD_POSTGRES_HOST: "todo-db-svc"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: project
  name: todo-db-configmap
data:
  POSTGRES_DB: "todo_db"
  POSTGRES_USER: "todo_user"
  POSTGRES_PASSWORD: "todo_pass" # TODO: use Secret with SOPS here
  PGDATA: "/var/lib/postgresql/data/todo-data"
